-- ============================================================
-- SOLUÇÕES & DESTINOS — TABELA DE RECADOS (SUPABASE)
-- ============================================================
-- Cole este conteúdo no painel do Supabase:
-- SQL Editor → New query → colar → RUN
-- ============================================================

-- 1) Tabela dos recados
create table if not exists public.recados (
  id          bigint generated by default as identity primary key,
  nome        text,
  pais        text,
  iso         text,
  texto       text,
  data        text,
  status      text not null default 'pendente',
  criado_em   timestamptz not null default now()
);

-- 2) Liga a segurança por linha (RLS)
alter table public.recados enable row level security;

-- 3) Visitantes LEEM apenas os recados aprovados
drop policy if exists "leitura publica dos aprovados" on public.recados;
create policy "leitura publica dos aprovados"
  on public.recados for select
  to anon, authenticated
  using (status = 'aprovado');

-- 4) Visitantes ENViam recados, mas sempre como "pendente"
drop policy if exists "visitante envia recado" on public.recados;
create policy "visitante envia recado"
  on public.recados for insert
  to anon, authenticated
  with check (
    status = 'pendente'
    and char_length(coalesce(texto,'')) between 10 and 600
    and char_length(coalesce(nome,'')) <= 40
  );

-- 5) Moderador (logado) VÊ tudo, inclusive os pendentes
drop policy if exists "moderador ve tudo" on public.recados;
create policy "moderador ve tudo"
  on public.recados for select
  to authenticated
  using (true);

-- 6) Moderador APROVA / RECUSA
drop policy if exists "moderador atualiza" on public.recados;
create policy "moderador atualiza"
  on public.recados for update
  to authenticated
  using (true) with check (true);

-- 7) Moderador APAGA
drop policy if exists "moderador apaga" on public.recados;
create policy "moderador apaga"
  on public.recados for delete
  to authenticated
  using (true);
